# fly.toml app configuration file generated for git-tracker-prod on 2023-07-24T16:35:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "git-tracker-prod"
primary_region = "bog"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
